begin;

select plan(40);

select has_table('public', 'app_user_roles', 'app_user_roles exists');
select has_table('public', 'procurement_product_rules', 'procurement_product_rules exists');
select has_table('public', 'procurement_supplier_receipts', 'procurement_supplier_receipts exists');
select has_table('public', 'procurement_supplier_reviews', 'procurement_supplier_reviews exists');
select has_table('public', 'procurement_audit_events', 'procurement_audit_events exists');

select col_is_pk('public', 'procurement_product_rules', 'product_code', 'product rules use product_code as primary key');
select col_is_pk('public', 'procurement_supplier_reviews', 'product_code', 'supplier reviews use product_code as primary key');
select col_is_unique('public', 'procurement_supplier_receipts', 'odoo_receipt_line_id', 'receipt lines are idempotent by Odoo line id');
select has_function('public', 'procurement_actor_role', array['uuid'], 'actor role helper exists');

select is((select relrowsecurity from pg_class where oid = 'public.app_user_roles'::regclass), true, 'RLS enabled on app_user_roles');
select is((select relrowsecurity from pg_class where oid = 'public.procurement_product_rules'::regclass), true, 'RLS enabled on procurement_product_rules');
select is((select relrowsecurity from pg_class where oid = 'public.procurement_supplier_receipts'::regclass), true, 'RLS enabled on procurement_supplier_receipts');
select is((select relrowsecurity from pg_class where oid = 'public.procurement_supplier_reviews'::regclass), true, 'RLS enabled on procurement_supplier_reviews');
select is((select relrowsecurity from pg_class where oid = 'public.procurement_audit_events'::regclass), true, 'RLS enabled on procurement_audit_events');

select ok(not has_table_privilege('anon', 'public.app_user_roles', 'select'), 'anon cannot read app_user_roles');
select ok(not has_table_privilege('authenticated', 'public.app_user_roles', 'select'), 'authenticated cannot read app_user_roles');
select ok(not has_table_privilege('anon', 'public.procurement_product_rules', 'select'), 'anon cannot read product rules');
select ok(not has_table_privilege('authenticated', 'public.procurement_product_rules', 'select'), 'authenticated cannot read product rules');
select ok(not has_table_privilege('anon', 'public.procurement_supplier_receipts', 'select'), 'anon cannot read supplier receipts');
select ok(not has_table_privilege('authenticated', 'public.procurement_supplier_receipts', 'select'), 'authenticated cannot read supplier receipts');
select ok(not has_table_privilege('anon', 'public.procurement_supplier_reviews', 'select'), 'anon cannot read supplier reviews');
select ok(not has_table_privilege('authenticated', 'public.procurement_supplier_reviews', 'select'), 'authenticated cannot read supplier reviews');
select ok(not has_table_privilege('anon', 'public.procurement_audit_events', 'select'), 'anon cannot read audit events');
select ok(not has_table_privilege('authenticated', 'public.procurement_audit_events', 'select'), 'authenticated cannot read audit events');

select ok(has_table_privilege('service_role', 'public.app_user_roles', 'insert'), 'service role can write app_user_roles');
select ok(has_table_privilege('service_role', 'public.procurement_product_rules', 'insert'), 'service role can write product rules');
select ok(has_table_privilege('service_role', 'public.procurement_supplier_receipts', 'insert'), 'service role can write supplier receipts');
select ok(has_table_privilege('service_role', 'public.procurement_supplier_reviews', 'insert'), 'service role can write supplier reviews');
select ok(has_table_privilege('service_role', 'public.procurement_audit_events', 'insert'), 'service role can append audit events');
select ok(not has_table_privilege('service_role', 'public.procurement_audit_events', 'update'), 'service role cannot edit audit events');
select ok(not has_table_privilege('service_role', 'public.procurement_audit_events', 'delete'), 'service role cannot delete audit events');

select is(
  (select data_type from information_schema.columns where table_schema = 'public' and table_name = 'procurement_audit_events' and column_name = 'id'),
  'bigint',
  'audit event id matches the numeric API contract'
);
select is(
  (select is_identity from information_schema.columns where table_schema = 'public' and table_name = 'procurement_audit_events' and column_name = 'id'),
  'YES',
  'audit event id is generated by PostgreSQL'
);

insert into public.procurement_product_rules (product_code) values ('TEST-SKU');
select is((select lead_time_days from public.procurement_product_rules where product_code = 'TEST-SKU'), 4, 'default lead time is four days');
select is((select safety_stock_days from public.procurement_product_rules where product_code = 'TEST-SKU'), 7, 'default safety stock is seven days');
select is((select version from public.procurement_product_rules where product_code = 'TEST-SKU'), 1::bigint, 'product rule version starts at one');

insert into public.procurement_supplier_reviews (product_code) values ('TEST-SKU');
select is((select status from public.procurement_supplier_reviews where product_code = 'TEST-SKU'), 'PENDING_REVIEW', 'supplier review starts pending');
select is((select version from public.procurement_supplier_reviews where product_code = 'TEST-SKU'), 0::bigint, 'supplier review version starts at zero');

select is(
  (select count(*)::integer from pg_policies where schemaname = 'public' and tablename in (
    'app_user_roles',
    'procurement_product_rules',
    'procurement_supplier_receipts',
    'procurement_supplier_reviews',
    'procurement_audit_events'
  )),
  0,
  'new application tables expose no browser policies'
);
select is(public.procurement_actor_role(gen_random_uuid()), null::text, 'unknown users receive no application role');

select * from finish();
rollback;
